# Generated by Django 5.2.4 on 2025-07-25 19:50

import django.core.validators
import usuarias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Nombre único para identificar a la usuaria', max_length=50, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(help_text='Correo electrónico de la usuaria', max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="El número debe estar en formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('role', models.CharField(choices=[('ADMIN', 'Administradora'), ('EMPLOYEE', 'Empleada'), ('MANAGER', 'Gerente')], default='EMPLOYEE', max_length=20, verbose_name='Rol')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('INACTIVE', 'Inactiva'), ('SUSPENDED', 'Suspendida')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('avatar', models.ImageField(blank=True, help_text='Foto de perfil de la usuaria', null=True, upload_to=usuarias.models.usuaria_avatar_upload_path, verbose_name='Avatar')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Contratación')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario')),
                ('address', models.TextField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Usuaria',
                'verbose_name_plural': 'Usuarias',
                'db_table': 'usuarias',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username'], name='usuarias_usernam_ea1d4d_idx'), models.Index(fields=['email'], name='usuarias_email_87bcc8_idx'), models.Index(fields=['role'], name='usuarias_role_90a3e5_idx')],
            },
        ),
    ]
