# Generated by Django 5.2.4 on 2025-07-15 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(max_length=20, unique=True)),
                ('legal_name', models.CharField(max_length=150)),
                ('tax_id', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.location')),
                ('payment_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paymentterm')),
                ('vat_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vatrate')),
            ],
        ),
    ]
