# Generated by Django 5.2.4 on 2025-07-25 19:49

import prenda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción detallada del producto', max_length=500, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Sube una imagen del producto (formatos: JPG, PNG, WEBP)', null=True, upload_to=prenda.models.product_image_upload_path, verbose_name='Imagen del Producto'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
    ]
