# Generated by Django 5.2.4 on 2025-07-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoría', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre de Categoría'),
        ),
    ]
