# Generated by Django 5.2.4 on 2025-07-19 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveBigIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='prendas')),
                ('Categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prendas', to='categorias.categoria')),
            ],
        ),
    ]
